### ISSUE TITLE
Why pushing is not  in scope

### ISSUE THREAD

**Issue by HuKeping** [kubernetes-incubator/cri-o#175]
Hi there,

Doesn't the pulling images and pushing images is a pair of operations? Then why the pulling is in scope but pushing not? The same question for verifying and signing.

**Comment by cyphar** [comment]
OCID is an executor for Kubernetes (namely the kubelet part of Kubernetes). Kubernetes requires the ability for a runtime to pull (and optionally verify) images from a remote repository, but doesn't require the inverse operations (pushing and signing). So there's no point in us implementing it if kubelet won't ever use it.

If you want to deal with pushing/pulling or signing/verifying you can contribute to the Open Container Initiative projects. This project is *specifically* for implementing the Kubelet CRI (container runtime interface) and nothing more.

**Comment by HuKeping** [comment]
Clear enough, thanks @cyphar ! Closing.

**Comment by rhatdan** [comment]
Take a look at https://github.com/containers/image for pushing/signing.  OCID is using this for pulling but other tools like https://github.com/projectatomic/skopeo/ and https://github.com/projectatomic/atomic are using it for pulling and pushing.

OCID is all about running containers for Kubernetes but some of the subprojects are goaled at being the building blocks of a full container image infrastructure.   These other projects are always looking for contributors also.

**Comment by HuKeping** [comment]
Thanks for those ref links @rhatdan ! It's helpful!

**Comment by HuKeping** [comment]
@rhatdan what's the purpose of https://github.com/containers/image , it seems like duplicated with OCI/image-tools , if so then why cri-o choose to use container/image instead of OCI/image-tools?

**Comment by cyphar** [comment]
@HuKeping It isn't a duplicate project. the OCI image-tools are for handling of OCI images (such as extracting OCI images). The OCI tooling doesn't support any other image format. https://github.com/containers/image is a library that allows you to translate between different image formats.

In particular, we need to be able to translate from Docker images to OCI images (which is supported by https://github.com/containers/image). If you play around with https://github.com/projectatomic/skopeo you'll better understand what the purpose of https://github.com/containers/image is -- it allows for **translation** between image formats.

Also, https://github.com/containers/storage is a fork of Docker (where we've just extracted the storage drivers) so that you can create a rootfs for a container using `btrfs` snapshots or other advanced union setups (as opposed to the OCI image-tooling which can only extract to a directory).

**Comment by HuKeping** [comment]
Thanks @cyphar !

Yes, I have also been aware of the  https://github.com/containers/storage project, but haven't got a time to look deeper into it.

I have a quick taste of  `skopeo`, I think it's a cool utility for many image related operations but it seems we may not use it in production.

As you mentioned above , the https://github.com/containers/image  can do the **translation** things between different image formats, do you imply that's what the OCI image-tools lack of? If so, do you think OCI image-tools and https://github.com/containers/image could be possible the alternative component for each other in the case of cri-o?

**Comment by HuKeping** [comment]
Furthermore, if one day in the future the container community stop fighting with each other and make a compromise that all compliant to OCI, do we still have those questions?

**Comment by cyphar** [comment]
The OCI does not define distribution, so you need to have some way of pulling images. containers/image also provides this functionality (for both Docker and AppC images).

> do you imply that's what the OCI image-tools lack of?

Kubernetes currently doesn't handle any of the "image pulling" -- everything is left up to us. That means that we have to pull images *somehow*. Since the OCI currently doesn't (for very complicated political reasons) support distribution at the moment, we have to pull Docker images and translate them to OCI images. We don't really have a choice here, and the OCI image-tools will never support such a workflow (because it requires using non-OCI images).

I'm hoping that once distribution becomes part of the OCI we can remove this, but to be honest I think containers/image is actually an incredibly useful project because it means that we can interoperate between AppC and OCI images (two different standards). While rkt is planning on integrating OCI support into their project, I still think it's quite useful to have a translation tool to keep everything in check (not to mention that I doubt Docker will ever support the OCI image spec fully).

> Furthermore, if one day in the future the container community stop fighting with each other and make a compromise that all compliant to OCI, do we still have those questions?

Once distribution is sorted out in the OCI, it might be possible to remove the need for containers/image. But I don't really see why it's such a big problem to be honest (it's actually kinda cool IMO).

> I have a quick taste of skopeo, I think it's a cool utility for many image related operations but it seems we may not use it in production.

At SUSE we're actually planning on using it as part of our build system so that we can use purely-OCI tooling to generate an OCI image and then translate it to a Docker image. Should be pretty cool :D.

**Comment by rhatdan** [comment]
I would say container/image is also about pulling and pushing of images from registries.  We also are building the first version of "simple image signing" into containers/image.  One thing we need to do is improve the README.md with some of the comments above, so the next reader of the github page does not get the same confusion.

The way I describe OCID (cri-o) is build of componants.  OCID being the Kubernetes CRI tool, when it gets a request from the kublet to run a new container, it will call into containers/image to make sure the image is on the host, if not containers/image will pull the image to the host and use containers/storage to store the image on disk.  OCID will then generate a OCI Specification for running the container and will execute opencontainer/runc (Or alternative container runtime) to launch the container.

**Comment by HuKeping** [comment]
Wonderful explanation about the workflow @rhatdan ! Thank you! I think I get much more clear about OCID now lol.

> for very complicated political reasons

Can't agree more  @cyphar ! lol

> Once distribution is sorted out in the OCI, it might be possible to remove the need for containers/image. But I don't really see why it's such a big problem to be honest (it's actually kinda cool IMO).

I think you're right, after a deeper digging into it I found it's really cool!
Thank you @cyphar  for all the kindly answers !

Closing.
