### ISSUE TITLE
Add support for sysctls

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#198]
Sysctls are passed as annotations in CRI. We need to process those keys in annotations and set sysctls in the runc config.json.

See http://kubernetes.io/docs/admin/sysctls/#safe-vs-unsafe-sysctls
https://github.com/kubernetes/kubernetes/pull/36728/files

**Comment by feiskyer** [comment]
Cool. We may also consider AppArmor and Seccomp, which are also passed in annotations.

**Comment by mrunalp** [comment]
Yeah can you create an issue for that?

**Comment by feiskyer** [comment]
@mrunalp OK.

**Comment by mrunalp** [comment]
Any taker for this one? @mikebrow ?

**Comment by Crazykev** [comment]
If no one take this yet, I'd love to do it.
            On 11/18/2016 01:41, Mrunal Patel wrote:Any taker for this one? @mikebrow ?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kubernetes-incubator/cri-o","title":"kubernetes-incubator/cri-o","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kubernetes-incubator/cri-o"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrunalp in #198: Any taker for this one? @mikebrow ?"}],"action":{"name":"View Issue","url":"https://github.com/kubernetes-incubator/cri-o/issues/198#issuecomment-261315688"}}}

**Comment by mrunalp** [comment]
@Crazykev sure, assigned to you :)

**Comment by rhatdan** [comment]
Do we handle ulimits?

**Comment by mrunalp** [comment]
@rhatdan CRI doesn't have support for it. Will check if it needs to be added there.
