### ISSUE TITLE
Read command from ContainerCreateRequest

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#260]
Right now we're only reading from `GetArgs()` at https://github.com/kubernetes-incubator/cri-o/blob/master/server/container_create.go#L124. (we need to fix `GetArgs()` override also in https://github.com/kubernetes-incubator/cri-o/pull/189#discussion_r91918788 but that's another story for now) 

That works like:
```sh
$ kubelet run nginx --image=nginx -- nginx '-g' 'daemon off;'
```
However something like:
```sh
$ kubelect run nginx --image=nginx --command -- nginx '-g' 'daemon off;'
```
isn't working at all and just use the default `/bin/sh` arg at https://github.com/kubernetes-incubator/cri-o/blob/master/server/container_create.go#L126

We should fix this by reading from both and maybe prefer `args` I guess /cc @jjlakis 

I'm fixing this right now so assigning this to me.

**Comment by jjlakis** [comment]
Looks like kubelet prefers `command` field (kubectl run --help):
`--command[=false]: If true and extra arguments are present, use them as the 'command' field in the container, rather than the 'args' field which is the default.`
IMO, we should pass all `<everything_in_command> <everything_in_args>` to be sure. It's natural that some will put all the arguments to `command`, some to `args`, and another will put command to the `command` and its arguments to `args`. Order is OK regarding of this.
