### ISSUE TITLE
Build fails on i586

### ISSUE THREAD

**Issue by cyphar** [kubernetes-incubator/cri-o#302]
Currently it's failing inside OBS for openSUSE: https://build.opensuse.org/package/live_build_log/home:cyphar:containers/ocid/openSUSE_Tumbleweed/i586

```
[   39s] go build --tags "exclude_graphdriver_aufs apparmor selinux seccomp" -o ocid ./cmd/server/
[   49s] # github.com/kubernetes-incubator/cri-o/oci
[   49s] vendor/src/github.com/kubernetes-incubator/cri-o/oci/oci.go:328: cannot use st.Ctim.Sec (type int32) as type int64 in argument to time.Unix
[   49s] vendor/src/github.com/kubernetes-incubator/cri-o/oci/oci.go:328: cannot use st.Ctim.Nsec (type int32) as type int64 in argument to time.Unix
```

**Comment by jawnsy** [comment]
We should add cross-compile builds for any of the architectures we intend to support, which thankfully can be done pretty easily with Go using `GOARCH`.  I think Docker only officially supports Linux on amd64 currently. I assumed we'd be starting with Linux and amd64-only for now? And I thought `time.Unix` always uses int64, regardless of platform: https://golang.org/pkg/time/#Unix - where is the int32 coming from?

**Comment by cyphar** [comment]
> We should add cross-compile builds for any of the architectures we intend to support, which thankfully can be done pretty easily with Go using GOARCH.

I'm not suggesting we intentionally create cross-compilation builds, I'm just keeping track of build issues that we will have to fix within our packages and should probably push the fixes upstream too. In particular, this fix is quite trivial (you create a separate source file that only builds on `i586` which has the right cast -- because Go doesn't like "useless" `int64(...)` casts).

> I think Docker only officially supports Linux on amd64 currently.

I can't comment on what Docker Inc supports, but SUSE supports Docker on a wide variety of architectures (including `i586`, `ppc64le` and `s390x`). I also think that Docker supports more architectures than they used to.

> And I thought time.Unix always uses int64, regardless of platform: https://golang.org/pkg/time/#Unix - where is the int32 coming from?

It's coming from `syscall.Stat_t`.

**Comment by jawnsy** [comment]
> I'm not suggesting we intentionally create cross-compilation builds

I know, I'm just suggesting that we could've found this bug earlier (in our Travis builds) if we were doing a cross-compile to x86.

> I can't comment on what Docker Inc supports, but SUSE supports Docker on a wide variety of architectures 

I think many vendors (Debian, Fedora) support more architectures than the upstream project, but this seems like a risky position to me. "It compiles and seems to work" is a far cry from "it's an officially supported platform", so if x86, ppc64le, s390x are architectures we want to support, it's preferable to do that upstream in cri-o itself (rather than have it handled independently by all vendors).

So, where possible, I think we should at least have infrastructure to cross-compile to those platforms, to make sure that we can at least build. It wouldn't catch all bugs, as we couldn't run the test suite without fully emulating those microarchitectures (slooow) but it'd be a good start.

**Comment by rhatdan** [comment]
@jawnsy Is this still an issue?

**Comment by jawnsy** [comment]
It's still failing [0], but upon deeper reflection, I'm not sure it matters -- moby/docker only supports x86-64, so perhaps i586 should be excluded from the SUSE RPM definition (in other words, it shouldn't attempt to build on i586 at all).

@cyphar thoughts? Does it make sense to have CRI-O runnable on 32-bit x86?

[0] https://build.opensuse.org/package/live_build_log/home:cyphar:containers/crio/openSUSE_Leap_42.1/i586

**Comment by runcom** [comment]
This is also happening in rawhide with go1.9 beta
