### ISSUE TITLE
Make discussion

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-incubator/cri-o#330]
So when we run make with the current build it uses "go install" which outputs to the user's go/bin directory for each of the binaries.  Then with a later request "make install" copies from go/bin to /user/local/bin.  

But when you run "make localintegration" it runs go install again for each of the binaries, presumably there's a dependency issue.

The developer now needs to make sure he checks his which for the binaries to know which he's running the one in his go/bin or the one in his /user/local/bin.

Sort of confusing here that we are using go install during a make. I suppose these changes were made to make the binaries go installable?  But I have to ask, why? Do we really need or even want to be able to install these binaries to the go/bin path from the cri-o repository before we then install them to /user/local/bin?

**Comment by runcom** [comment]
We should be able to support installing under "_output" as k8s or openshift does

**Comment by mikebrow** [comment]
Yes, we should probably be doing make targets a bit more like k8s:
```
OUT_DIR ?= _output
BIN_DIR := $(OUT_DIR)/bin
```
Right now we have:
```
PREFIX ?= ${DESTDIR}/usr/local
BINDIR ?= ${PREFIX}/bin
```
Where BINDIR is used as the for "make install."

Currently $GOPATH/bin is the target for make because we started using go install to build instead of go build, thus the source for the make install is set to $GOPATH/bin.  

I presume this was done so we could do go get download installs of the binaries to simplify standalone use of the binaries?

We should be able to exploit the "-pkgdir" option to push output to _output...

**Comment by jawnsy** [comment]
@mikebrow The main reason was to be able to leverage the package cache, but being able to `go get` to install `ocic` is a nice side effect, I think. I don't have any objection to using `-pkgdir` though.

I've just never personally understood why so many prominent Go projects (like Kubernetes) insist on using a non-standard install process - what's the advantage of `_output` over what we're doing today?

Either way, you're installing the binaries somewhere (whether `GOPATH/bin` or `_output/bin`) and needing to copy them to `/usr/local` when you `sudo make install`, right?

I guess the main advantage is that you can clone anywhere, instead of cloning into your `GOPATH` (which I personally find strange, but this is the way Go seems to have been designed, and when in Rome...)

> But when you run "make localintegration" it runs go install again for each of the binaries, presumably there's a dependency issue.

This seems like a bug to me; if you `make localintegration` it should be able to detect that everything was already built/installed to the `GOPATH` or `_output` directory or wherever. In fact, `make install` should not be mandatory for running tests as the daemon should be run directly from the `GOPATH/bin`; in `helpers.bats`, we have:

```bash
OCID_BINARY=${OCID_BINARY:-${GOPATH}/bin/ocid}
```

**Comment by mikebrow** [comment]
I clone into my gopath  
```
GOROOT=/usr/local/go
GOPATH=/home/mike/go
pwd=/home/mike/go/src/github.com/kubernetes-incubator/cri-o 
```
k8s.io does it weird for a number of reasons.. their package names in github don't match their path in github.. that's odd and apparently is a historical issue given that it wasn't github in the beginning. To make the go tools work well with kube builds I have to clone kube into:
```
/home/mike/go/src/k8s.io/kubernetes
```

The advantage of "_output" is similar to our advantage of using "DESTDIR."  

Yes the binaries have to go somewhere.. k8s has the extra step of building a "plethora" of installable binaries for various platforms.  We'll have to fit into that somehow.  

I agree with the in Rome thing.. but when doing a make.. one typically does not expect an install to occur other than possibly a binary being located in "/bin" or " ./" or "./bin" or some other output directory of convenience which is by default not typically already on one's executable path.  IOW I don't expect a build to overwrite a previously installed binary. I expect it to build local and allow me the opportunity to install anywhere I want. What we've done with the make target being $gopath/bin is force me the developer to backup my $gopath/bin if that's where I'm running ocid as a default product.

Yeah not sure what's up yet, but running make repeatedly shows that the make dependencies need some work.

**Comment by jawnsy** [comment]
I'll experiment with `-pkgdir` & `_output` later - looks like that flag works with both `go install` and `go test`. It would definitely make cleaning easier (`rm -rf _output` versus trying to clean the $GOPATH without messing up other stuff that might be in there)

My change (using $GOPATH/bin) there is a bit buggy, as it doesn't work with multi-part GOPATHs. I guess using `_output` might make this better.
