### ISSUE TITLE
Logo for cri-o

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#370]
We should have a logo for cri-o :)

**Comment by mairin** [comment]
I did a logo design, you can feel free to use it:

![cri-o](https://cloud.githubusercontent.com/assets/799683/23230497/34d275f8-f912-11e6-98dd-7e818c2fe5d0.png)

Here's the SVG source (wrapped in a zip, sorry! Github won't support SVG)
[cri-o_logo_SVG.zip](https://github.com/kubernetes-incubator/cri-o/files/794704/cri-o_logo_SVG.zip)

I did a little blog write up of the idea behind it here:
http://blog.linuxgrrl.com/2017/02/22/a-logo-for-cri-o/

**Comment by cyphar** [comment]
@mairin What license is the logo under [preferably CC-BY 4.0]?

**Comment by mairin** [comment]
@cyphar So here's the thing with logos and licensing - you really don't want to use an open license like CC for a logo, because you then wouldn't be able to reinforce a trademark on it. If your project has a contributor agreement or copyright assignment kind of policy / document, I'm happy to sign it, otherwise you can consider this comment to grant the cri-o project an unlimited use license to use, relicense, trademark, or anything else the project would like to do with this logo design in perpetuity.

**Comment by mairin** [comment]
(Also of note, the font used is Montserrat, an Open Font License font. Just good to know; shouldn't have any bearing on the licensing of the mark itself.)

**Comment by jawnsy** [comment]
@mairin Sounds like the logo has been really well-received by the community, so I think we should move toward adding it to the repository. Could you open a PR to add these to the repository? The PR could include creating a PNG version of the top logo (since it has a white background) and incorporating it in the README.md.

You will need to sign the CNCF CLA if you haven't already: https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md#contributor-license-agreements

If you're busy, I'm happy to do this on your behalf, we're all just really excited to put this logo in a prominent place :smile:

**Comment by cyphar** [comment]
@mairin Our CLA is not a copyright assignment, but it does give the CNCF rights similar to Apache (from my reading). So it should be sufficient.

**Comment by mairin** [comment]
Hey I signed the CNCF CLA; I may be making mods to the logo though so not going to do the PR request just yet. (Have gotten negative feedback about the fact it's a snowflake, e.g. https://www.sumologic.com/blog-devops/snowflake-configurations-and-devops-automation/ )

**Comment by jawnsy** [comment]
I'm familiar with that connotation of snowflakes, but personally I think the snowflake logo is fine. Maybe we could hold a community vote to figure out what people like the best?

IMO, I love the current logo and think we should just merge it, even if we're working on improving it later. It's not being etched in stone, and the project is still alpha anyway, so I don't think there's any reason not to merge a first iteration.

:snowflake:

**Comment by mairin** [comment]
Ok cool! Will file a PR shortly then while thinking about potential alternatives in the meanwhile.

**Comment by mairin** [comment]
see https://github.com/kubernetes-incubator/cri-o/pull/376

**Comment by cyphar** [comment]
I like the snowflake (I think trying to make a logo around cryogenics is going to be a bit difficult). The only complaint I have is that it's a bit odd to have two _slightly different_ shades of blue in the snowflake (especially since it's replicated but the colour applies to less than half of each shard).

But as @jawnsy said these are all just details and we should merge the current logo and work on improving it later.

Thanks for this @mairin. :tada:

**Comment by mairin** [comment]
Hey @cyphar each snowflake should only have one shade of blue; I changed the shade slightly on one of the versions of the snowflake (I think the gradient one) so it would read better against that particular gradient (is that what you meant?)

**Comment by runcom** [comment]
we do have it now no? :smile:
