### ISSUE TITLE
[RFC] kpod Command Line Discussion

### ISSUE THREAD

**Issue by mheon** [kubernetes-incubator/cri-o#490]
I've started implementing some CLI commands for `kpod`, and realized that I didn't have a solid grasp on how to lay out the CLI for common commands. @mrunalp had a good idea where he wanted to go with it, but we agreed it was reasonable to put it up for comment and discussion.

The way I've been thinking of approaching it is to split the CLI into separate commands for containers and pod operations (tentatively, `kpod pod` and `kpod ctr`) with further commands (`launch`, `list`, `remove`, `get`) for each - so `kpod pod launch` to launch a new pod, `kpod ctr remove` to remove a container, etc. Container operations would mostly require a target pod be given (save things like `list`). The downside of this is a that it ends up more verbose than just switching between acting on a single container or a whole pod with flags.

**Comment by mheon** [comment]
@mrunalp You had a different way of laying out commands, but I don't remember it well enough to write it out myself, so I'll leave that to you

**Comment by jberkus** [comment]
so removing a container would be:

```
kpod ctr remove my-pod my-container
```

... seems pretty logical and easy to remember.

The alternative, since for container operations you pretty much always need to list a pod, would be to *imply*.  That is, if I type `kpod remove my-pod` it removes the pod, but `kpod remove my-pod my-container` removes the container from the pod.  That would save typing, except that it wouldn't work for all commands.

**Comment by rhatdan** [comment]
We have moved kpod to following the docker syntax for commands.  I think that is simplest and easiest for people to convert.  I think we should close this issue.

@mrunalp @runcom Please close this.
