### ISSUE TITLE
storage images IDs leak and performance

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#500]
If you keep pulling the same image you'll see multiple equal entries in `ocic image list`:
```
9:03:02 [github.com/kubernetes-incubator/cri-o] ‹master*› sudo ./ocic image list
9:03:07 [github.com/kubernetes-incubator/cri-o] ‹master*› sudo ./ocic image pull redis:alpine
9:03:28 [github.com/kubernetes-incubator/cri-o] ‹master*› sudo ./ocic image list
ID: daf0566b996b78b0513860fb68d76d21764ce0082dcafb3a3c05b08928a11983
Tag: docker.io/library/redis:alpine
9:03:31 [github.com/kubernetes-incubator/cri-o] ‹master*› sudo ./ocic image pull redis:alpine
9:03:47 [github.com/kubernetes-incubator/cri-o] ‹master*› sudo ./ocic image list
ID: daf0566b996b78b0513860fb68d76d21764ce0082dcafb3a3c05b08928a11983
Tag: docker.io/library/redis:alpine
ID: ab72efadb0c96fbea19df4bf8be0ae8b22200a59aa0a35caf6901f1731eef831
Tag: docker.io/library/redis:alpine
9:03:49 [github.com/kubernetes-incubator/cri-o] ‹master*› time sudo ./ocic image pull redis:alpine
sudo ./ocic image pull redis:alpine  0.06s user 0.01s system 0% cpu 14.654 total
9:04:12 [github.com/kubernetes-incubator/cri-o] ‹master*›
9:04:33 [github.com/kubernetes-incubator/cri-o] ‹master*›
9:04:33 [github.com/kubernetes-incubator/cri-o] ‹master*› time sudo ./ocic image pull nginx:alpine
sudo ./ocic image pull nginx:alpine  0.06s user 0.01s system 0% cpu 15.125 total
9:04:57 [github.com/kubernetes-incubator/cri-o] ‹master*› sudo ./ocic image listID: daf0566b996b78b0513860fb68d76d21764ce0082dcafb3a3c05b08928a11983
Tag: docker.io/library/redis:alpine
ID: ab72efadb0c96fbea19df4bf8be0ae8b22200a59aa0a35caf6901f1731eef831
Tag: docker.io/library/redis:alpine
ID: 60b62b3616748bc3c52554e5cc8737716e72fa084f3261c889499c57b2fa97ca
Tag: docker.io/library/redis:alpine
ID: c371cd6b72f13366c3a38488c47bf98b2dc03ec7b0572b1bc52e97229fdc22be
Tag: docker.io/library/nginx:alpine
9:05:05 [github.com/kubernetes-incubator/cri-o] ‹master*› time sudo ./ocic image pull nginx:alpine
sudo ./ocic image pull nginx:alpine  0.06s user 0.01s system 0% cpu 12.137 total
9:05:21 [github.com/kubernetes-incubator/cri-o] ‹master*› time sudo ./ocic image pull nginx:alpine
sudo ./ocic image pull nginx:alpine  0.06s user 0.01s system 0% cpu 12.104 total
9:05:36 [github.com/kubernetes-incubator/cri-o] ‹master*› time sudo ./ocic image pull nginx:alpine
sudo ./ocic image pull nginx:alpine  0.06s user 0.02s system 0% cpu 13.101 total

9:05:57 [github.com/kubernetes-incubator/cri-o] ‹master*› sudo ./ocic image listID: daf0566b996b78b0513860fb68d76d21764ce0082dcafb3a3c05b08928a11983
Tag: docker.io/library/redis:alpine
ID: ab72efadb0c96fbea19df4bf8be0ae8b22200a59aa0a35caf6901f1731eef831
Tag: docker.io/library/redis:alpine
ID: 60b62b3616748bc3c52554e5cc8737716e72fa084f3261c889499c57b2fa97ca
Tag: docker.io/library/redis:alpine
ID: c371cd6b72f13366c3a38488c47bf98b2dc03ec7b0572b1bc52e97229fdc22be
Tag: docker.io/library/nginx:alpine
ID: 1453325e53a29360acd1596f958fe3dc975dfeb6221d67c87fd25211f4f9a50a
ID: 2da89ea96cbcfd9d7fac4a185a3227e8074a694d1d55051dc699d659ff195e92
ID: b0bfb6d0c11c093bfb5323f0761a460e973d742c17d9cc39f9c1fd8b794ad785
Tag: docker.io/library/nginx:alpine
9:08:56 [github.com/kubernetes-incubator/cri-o] ‹master*›
```
As for performance, 15s to pull the first image and ~12-13s to pull the same exact image isn't that good. From logs, we keep re-pulling each blob/layer each time whether we should just use the image config digest to see if the image is already on disk (thanks to content addressable storage we should be able to replicate what docker does, not sure this need a lot of changes to c/storage though).

Last thing: @nalind notice how the last image listing stacks all the `nginx:alpine` images while `redis:alpine` aren't stacked together, do you know why?

@nalind @mtrmac PTAL

**Comment by runcom** [comment]
@mtrmac @nalind I've also noticed we first copy layers in c/image's `copy` and then config. We should come up with something to check for config first...

**Comment by mtrmac** [comment]
> I've also noticed we first copy layers in c/image's copy and then config. We should come up with something to check for config first...

Why does that matter? (We do it this way because config format depends on supported schema in the output; i.e. we always copy the same layers, but we may try several config+manifest formats until one is accepted.)

(To be pedantic, do you have data indicating that the time is really spent copying layers? It _is_ a good guess, to be sure.)

Ideally `storageImageDestination.HasBlob` should detect that the layers are present and avoid copying them. That did work at some point IIRC. Though looking at it now, it only looks at `s.BlobList`, which is not populated from the containers/storage backing store in `newImageDestination`, AFAICS.

**Comment by mtrmac** [comment]
(Broadly speaking, IIRC from conversations in https://github.com/containers/image/pull/63 , c/storage, or perhaps the combination of c/storage+c/image, had difficulties in identifying layers using the uncompressed vs. compressed digests, when the necessary values are not always available. But I’ll leave that up to @nalind as an expert.)

**Comment by rhatdan** [comment]
@nalind Is this still an issue?

**Comment by nalind** [comment]
When the image is being pulled multiple times, it's getting assigned a new ID each time, and the tag is being moved to the most-recently-pulled copy each time.  (The output of `ocic image list` lists each image's ID, then its zero or more tags.)

HasBlob() doesn't currently detect "blobs" that are part of images that have previously been pulled, since they aren't blobs any more at this point.  Some of the features we've added to containers/storage recently make it easier/possible to look for the content locally using when-they-were-compressed and uncompressed digests.

I've been working on changes to teach the image library to use the digests to make HasBlob() smarter, and can work on the assigning-new-IDs part while working on getting the smaller bits that were pared off as separate PRs to past review.
