### ISSUE TITLE
image digests TODOs and bugs

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#531]
@nalind @mtrmac here's the situation:

- when pulling an image by tag we need to **always** store the digested reference along with the tag (same as docker does)
- we don't have a `RepoDigests` for `ImageStatus` and we just fill `RepoTags` with `status.Names` which just contains tagged references for that image
- (guess what) we need `RepoDigests` slice
- digests must not be stored and shown as the ID of an image (see reproducer 1). The image ID in docker is the digest of its `config` blob which should be unique due to content addressability!
-  if you pull an image by digest corresponding to a tag different than `latest` image list reports that it has a `:latest` tag whether that's not true at all (see reproducer 2)
- image ID should be the config blob digest!

--

reproducer 1 (digest shown as image ID, the image ID should be the `config` digest blob!):
```
$ crioctl image pull nginx@sha256:4aacdcf186934dcb02f642579314075910f1855590fd3039d8fa4c9f96e48315
$ crioctl image list
ID: 4aacdcf186934dcb02f642579314075910f1855590fd3039d8fa4c9f96e48315
Tag: docker.io/library/nginx:latest
```

--

reproducer 2 (wrong tag applied to a digested image, there should not be any tag for this image unless someone has previously pulled the same image by tag, in which case we already have the digest as well):
```sh
# this is the digest for redis:alpine but redis:latest is shown below, incorrectly
# notice how the same issue as reproducer 1 is shown below (ID != digest)
$ crioctl image pull redis@sha256:03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b
$ crioctl image list
ID: 03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b
Tag: docker.io/library/redis:latest
```

**Comment by mtrmac** [comment]
@runcom Is there anything specific I should be doing?

FWIW it may not be _obviously necessary_ to exactly replicate the Docker config digest / manifest digest dichotomy, if the CRI API does not already embed the assumption that this is the way it works

As long as truly different images are not mixed together, it may make sense to e.g. identify images by manifest digest and ignore config digests completely (I guess, as long as layer chains _are_ deduplicated, because that costs disk space).

**Comment by runcom** [comment]
@mtrmac wasn't the whole idea of using the config blob digest to be content-addressable? I keep hearing that all over the places and using the manifest digest sounds, instead, weird to me.

**Comment by mtrmac** [comment]
@runcom This tends towards a philosophical question… The same way you can have two equivalent manifests with different digests, you can have two equivalent configs with diffrent digests, if only because of whitespace. Hence, there will always be “equivalent” images which have different IDs, and that’s really fine.

(It is, _also_, perfectly fine to implement the `docker`-like config+manifest model, if that’s what you want; all I wanted to point out is that it is not _obviously necessary_, e.g. it may be less confusing for users if there is only one kind of ID. … But then users already know the two kinds of `docker`-originated IDs, and introducing a third, different, kind of ID would I guess be worse.)

**Comment by runcom** [comment]
@mtrmac, crystal clear, I guess the rest of the issue is for @nalind then

**Comment by rhatdan** [comment]
@runcom Please update the status on this issue?

**Comment by runcom** [comment]
@rhatdan we would love @nalind to tackle this in c/storage

**Comment by nalind** [comment]
Now that #1116 is in, I _think_ these all work as expected?
* Images pulled using tags can be located using digested (canonical) references.
* Images pulled using canonical references don't have a tag added to them.
* We should be populating image references in replies to PullImage, ImageStatus, ImageList, and ContainerStatus requests.
* Image IDs are stable, in that pulling the same image more than once, even if by different tags, should still result in image being stored locally, and that image can be located using any of the names which were used, or by using a canonical reference.
