### ISSUE TITLE
conmon: Support non-terminal attach 

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#569]
We need to support non-terminal attach. For that, we will have to send both stderr/stdout over the unix domain socket tcp connection to the client. @alexlarsson does glib have any utilities to support framing to handle this?

**Comment by 14rcole** [comment]
I don't know much about unix domain sockets, but glib has a struct called GUnixConnection with functions that allow sending and receiving of open file descriptors over a uds.  STDOUT_FILENO and STDERR_FILENO could just be passed to these in order to forward the data along, right?

Like I said, I don't know too much about unix domain sockets.  I always thought they were for inter-process communication so this method may not work over TCP.  If not, GSocket, a parent of GUnixConnection, has the function `g_socket_send_message` that may work, although the data written to stderr/stdout would have to be manually intercepted and sent.

**Comment by alexlarsson** [comment]
The easiest way would be to let the kernel do the framing, by using  a SOCK_SEQPACKET socket. Just send an initial byte which is the type of stream, and then the data. We just have to ensure that the recieving side uses a large enough buffer. I can take a look at this.
