### ISSUE TITLE
Is Kpod meant to be a linux only tool?

### ISSUE THREAD

**Issue by jorgemoralespou** [kubernetes-incubator/cri-o#621]
While looking into the project, kpod seems a tool any developer/admin could use to interact with a kubernetes/openshift platform, in that regards, it could be used from different Operating Systems.
I see that there is no binaries being released, but there are some issues targeting the creation of rpms and deb packages.

Also in the README, there is a comment:

> What is not in scope for this project?
> - A CLI utility for interacting with cri-o. Any CLIs built as part of this project are only meant for testing this project and there will be no guarantees on the backwards compatibility with it. 

Does this mean that kpod is part of what's considered a CLI utility and meant just for testing? If not, does it make sense to provide a compiled binary for users of different architectures to use?

**Comment by cyphar** [comment]
The (big picture, not current status) plans for kpod is that it will allow you to run `cri-o` operations without the cri-o daemon running (since the cri-o daemon isn't actually necessary, it only exists to provide a gRPC endpoint).

I'm not entirely sure what the plans are regarding the actual CLI interface (I haven't touched this project in a while or talked to @mrunalp about his plans in this regard), but I would expect that

However, the important thing to note is that kpod is **not** a gRPC client. It's sort of like taking the core bits of cri-o and making them single no-daemon operations (similar in some ways to how `rkt`'s model works). So it doesn't make sense to make binaries for `kpod` on platforms where you can't run `cri-o`.

**Comment by rhatdan** [comment]
Korrect.  kpod is only working on the back end of cri-o. Not talking to any daemons, So there is no plan to make it work on any platforms other then platforms that support cri-o.

**Comment by rhatdan** [comment]
@mrunalp Please close
