### ISSUE TITLE
Integrating storage

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#8]
Taken from https://github.com/mrunalp/ocid/issues/22, part of https://github.com/mrunalp/ocid/issues/6.

Depends on https://github.com/containers/image/pull/63 but we could actually start playing with this. This also depends on https://github.com/containers/image/pull/41 (wrt to have containers/image to receive an auth configuration to pull from registries), but not strictly, I'll work on that asap.

The way we get the image from the CRI API is hardcoding _docker_ as the reference and _docker registry_ as the transport, this is being worked on in https://github.com/kubernetes/kubernetes/issues/7203.

Pseudo code re-arranged:

``` go
import (
    "github.com/containers/image/copy"
    "github.com/containers/storage"
)

func PullImage(imageName) error {
    // imageName - as come from K8s API contains NAME+TAGORDIGEST
    if storage.IsAlreadyPulled(imageName) {
        return nil
    }

    src := // create an new ImageSource, probably from docker
    dest := // create a new OCIStorageDestination

    err := copy.Image(ctx, policyCtx, src, dest, options)
    if err != nil {
        return err
    }

    return nil
}

// then the image stored above is used to create a new container
func CreateContainerRootfs(id) error {
    imageMetadata = storage.GetMetadata(imageIDorName)
    storage.CreateContainer(imageID=..., optionalName=..., optionalID=..., metadata=...)
    // [ ... ]
}
```

@mrunalp @mtrmac @nalind PTAL

**Comment by nalind** [comment]
Pull looks about right to me.  We should need a Mount call after CreateContainer, but the heavy part after that is keeping track of the container's ID so that it can be reused, restarted, or eventually deleted.  If there's a shareable format for that information, it can be stashed in the storage library using SetMetadata() or SetBigData() and ocid can scan through the list returned by Containers() when it starts up (there should probably be a better way for ocid to discover when someone else has created or removed a container).  If not, and ocid's containers are specific to ocid, then it also has the option of tracking that information using its own mechanisms.

**Comment by runcom** [comment]
> Pull looks about right to me.

Great, I'm specifically tacking Pull as a first iteration to be merged in ocid. Thanks Nalin.
