### ISSUE TITLE
Update to kube 1.8

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#879]
Tracking changes from upstream kube 1.8 release branch https://github.com/kubernetes/kubernetes/commits/release-1.8/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto (and look also what's happening in the dockershim https://github.com/kubernetes/kubernetes/commits/release-1.8/pkg/kubelet/dockershim):

- ~~no_new_privs https://github.com/kubernetes-incubator/cri-o/issues/869~~
- ~~localhost seccomp profile https://github.com/kubernetes-incubator/cri-o/issues/202~~
- ~~update container resources~~
- ~~mount propagation~~
- ~~**container stats, imagefs info?** probably 1.9? we have cadvisor for now~~
- ~~correctly stop the streaming server https://github.com/kubernetes-incubator/cri-o/pull/852/files#diff-702431da3a2e35392cf253955d15f774R145~~
- ???

**Comment by runcom** [comment]
(assigning this to me as I've already done much of this in a branch)

**Comment by brancz** [comment]
> we have cadvisor for now

This is somewhat contradicting, as upstream is trying to get rid of the compiled in cAdvisor, but in order to be able to do that we're depending on CRI implementations to actually implement stats calls.

**Comment by runcom** [comment]
@brancz well, we will have something for stats calls for sure in the near future, but for now, we went successfully with cadvisor which is handling everything just fine. What's your concern in not using stats calls right now?

**Comment by brancz** [comment]
It's just a bit odd, that a project that effectively exists to implement an interface goes 1.0 before implementing the full interface:

* https://github.com/kubernetes-incubator/cri-o/blob/c04f585a53daca1f37f2b5110aed0112d451488e/server/container_stats_list.go#L12
* https://github.com/kubernetes-incubator/cri-o/blob/c04f585a53daca1f37f2b5110aed0112d451488e/server/container_stats.go#L13

And the problem is that kubernetes/kubernetes is trying to get rid of the cAdvisor dependency, but is relying on the CRI implementations to actually implement the interface in order for that to actually happen. To be completely honest, no CRI implementation currently implements this, not even dockershim. But all the CRI implementations keep saying "well the other implementations don't have it either so it's fine", and that's a problem.

Sorry for hijacking this issue, I just felt like it's something that needs to be brought up.
