### ISSUE TITLE
CRI-O scaling bug

### ISSUE THREAD

**Issue by sameo** [kubernetes-incubator/cri-o#956]
I'm using this issue as a tracker, I'm assigning it to myself.

Testing environment:

```sh
root@k8s-minion-1:~# crio --version
crio version 1.0.0-rc3-dev
commit: "c92d971930457978f85ff8635597a91d629ff2ed-dirty"

root@k8s-minion-1:~# runc --version
runc version 1.0.0-rc4+dev
commit: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
spec: 1.0.0

root@k8s-minion-1:~# kubelet --version
Kubernetes v1.7.5

root@k8s-minion-1:~# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

# The machine is a 4xIntel(R) Core(TM) i7-5557U CPU @ 3.10GHz with 16GB of RAM
```

Test description:

```sh
# Start kubernetes through kubeadm
root@k8s-minion-1:~# kubeadm init --pod-network-cidr 10.218.1.0/16

# Start flannel
root@k8s-minion-1:~# kubectl apply -f /home/samuel/flannel.yaml

# Start an expose an nginx deployment
root@k8s-minion-1:~# kubectl create -f nginx-deployment.yaml
root@k8s-minion-1:~# kubectl expose deployment nginx --port=80 --type=NodePort

# Scale the deployment out to 50 pods
root@k8s-minion-1:~# kubectl scale deployment nginx --replicas=50
root@k8s-minion-1:~# kubectl get pods -n default | grep Running | wc -l
50

# Scale the deployment out to 100 pods
root@k8s-minion-1:~# kubectl scale deployment nginx --replicas=50
root@k8s-minion-1:~# kubectl get pods -n default | grep Running | wc -l
100

# Scale the deployment out to 150 pods
root@k8s-minion-1:~# kubectl scale deployment nginx --replicas=50
root@k8s-minion-1:~# kubectl get pods -n default | grep Running | wc -l
103
```

We see that for some reasons we can't scale further than 103 pods (consistently 103). I verified that I can launch 300+ Docker containers on that machine and have them running at the same time.

**Comment by runcom** [comment]
> We see that for some reasons we can't scale further than 103 pods (consistently 103). I verified that I can launch 300+ Docker containers on that machine and have them running at the same time.

awesome, thanks for looking into this Sam

**Comment by sameo** [comment]
[crio.log](https://github.com/kubernetes-incubator/cri-o/files/1341241/crio.log)

**Comment by sameo** [comment]
[kubelet.log](https://github.com/kubernetes-incubator/cri-o/files/1341479/kubelet.log)

**Comment by sameo** [comment]
@nalind Maybe not related but we're seeing a bunch of:

```sh
Sep 28 16:12:45 k8s-minion-1 kubelet[2004]: E0928 16:12:45.891183    2004 kuberuntime_image.go:106] ListImages failed: rpc error: code = 2 desc = error decoding metadata for source image: unexpected end of JSON input
```

errors in the kubelet log.

**Comment by nalind** [comment]
The metadata that this error message is referring to is a field in a structure, in an array that's encoded in `${storageroot}/${storagedriver}-images/images.json`, so the next time you see it, please forward me a copy of the file and/or check if the `metadata` field is missing or the file's somehow been corrupted.

The format for the `metadata` field is private to the `containers/image` library, so if you're poking at it with tools that use different versions of that library, they might disagree about the format of the contents.  That's unlikely to be the cause for this error, though, because its contents would still look like valid JSON if they merely disagreed on the format, while the error message you're seeing suggests that the field's just empty.

That said, I _am_ working on a patch that will make the field obsolete (so it would start to be left empty), but it still needs work before it can be merged into `containers/image`, so that shouldn't be the cause, either.  I'm only mentioning it in the unlikely event that you're using one of the WIP versions of another tool on the same system.

**Comment by sameo** [comment]
So the 103 limitation is coming from kubelet's `--max-pod` maximum number of pods per node which defaults to 110 (103 + 7 pods for the control plane).
@nalind I will look into the storage issue, but it really seems to be related to aufs. When switching to overlay, I can not reproduce it.

**Comment by rhatdan** [comment]
@sameo Can I close this?

**Comment by sameo** [comment]
I'm closing that one and will open a specific issue for the storage part of that report.
